archive: check for archive_dir

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -5,14 +5,19 @@
 
 archive_dir="$HOME/archive"
 
+if [[ ! -d "$archive_dir" ]]; then
+    echo "error: archive directory $archive_dir does not exist"
+    exit 1
+fi
+
 if [[ $# == 0 ]]; then
     echo "error: expected at least 1 argument"
-    exit 1
+    exit 2
 fi
 
 if [[ $# > 2 ]]; then
     echo "error: too many arguments (expected 1 or 2)"
-    exit 2
+    exit 3
 fi
 
 if [[ $2 ]]; then
@@ -23,7 +28,7 @@ fi
 
 if [[ ! -e "$1" ]]; then
     echo "error: file/directory specified does not exist ($1)"
-    exit 3
+    exit 4
 fi
 
 file_to_archive="$1"
@@ -31,7 +36,7 @@ archive="$archive_dir/$(date +%Y-%m-%d)-${dest_archive##*/}.tar.xz"
 
 if [[ -e "$archive" ]]; then
     echo "error: output archive file already exists ($archive)"
-    exit 4
+    exit 5
 fi
 
 XZ_OPT=-9 tar -Jcvpf "$archive" "$file_to_archive"
@@ -40,5 +45,5 @@ if [[ $? == 0 ]]; then
     echo "Archived $file_to_archive to $archive"
 else
     echo "error: something went wrong while tarring"
-    exit 5
+    exit 6
 fi
