cs-shot: update, and it works now

diff --git a/cs-shot b/cs-shot
--- a/cs-shot
+++ b/cs-shot
@@ -7,9 +7,21 @@
 shot_dir="$HOME/school/report/img/test"
 shot_name="$(date +%F_%T)_cs-test-img.png"
 
-scrot "$shot_dir/$shot_name"
+# prompt for a test ID
 test_id="$(zenity --entry \
        --title="${0##*/}" \
        --text="Test ID:")"
-ln -s "$shot_name" "$shot_dir/
-shot_symlink=
+if [[ $? != 0 ]]; then
+    # fail early if they press Cancel or hit Escape
+    echo "Zenity failed, screenshot cancelled"
+    exit 1
+elif [[ -z "$test_id" ]]; then
+    # empty ID, fail
+    echo "No ID provided, screenshot cancelled"
+    exit 2
+fi
+
+echo "Taking a screenshot..."
+scrot "$shot_dir/$shot_name"
+ln -s "$shot_name" "$shot_dir/${test_id}.png"
+echo "Done."
